let salg = document.getElementById('salg')
let doces = document.getElementById('doces')
let pratos = document.getElementById('pratos')
let reserv = document.getElementById('reserv')
let p1 = document.getElementById('p1')
let r1 = document.getElementById('r1')
let p2 = document.getElementById('p2')
let r2 = document.getElementById('r2')
let p3 = document.getElementById('p3')
let r3 = document.getElementById('r3')
let img1 = document.getElementById('img1')
let img2 = document.getElementById('img2')
let img3 = document.getElementById('img3')

